Adding support for QR code generation
needs qrencode

diff --git a/wirego b/wirego
--- a/wirego
+++ b/wirego
@@ -1,9 +1,11 @@
 #!/bin/bash
 
+# wirego https://github.com/francescor/wirego
+
 # run:
 #   wirego # shot status and profiles 
 #   wirego down  # take wireguard vpn down
-#   wirego NAME  # take wireguard profile NAME.conf up (before take down any other active wireguard vpn) 
+#   wirego NAME  # take wireguard profile NAME.conf up (before take down any other active wireguard vpn)#   wirego qr    # show QR code (needs: qrencode)
 
 
 function list_profiles() {
@@ -30,6 +32,18 @@ fi
 
 parameter=$1
 
+# check existance of /etc/wireguard/
+if [ ! -d "/etc/wireguard" ]; then
+  echo "The directory /etc/wireguard does not exist, exiting"
+  exit 1
+fi
+
+# check existnace of wg
+if [ "`which wg`" == "" ] ; then
+  echo "cannot find wg: is Wireguard installed?"
+  exit 1
+fi
+
 # load all profiles
 profiles=`sudo  ls -1 /etc/wireguard/ | grep "\.conf" | awk -F'.' '{print $1}'`
 
@@ -49,6 +63,19 @@ if [ "$parameter" == "" ] ; then
   exit
 fi
 
+if [ "$parameter" == "qr" ] ; then
+  # check existnace of qrencode
+  if [ "`which qrencode`" == "" ] ; then
+    echo "cannot find qrencode, you need to install it"
+    exit 1
+  fi
+  echo "QR code generation"
+  list_profiles
+  echo -n "Enter profile for which you want to see the QR code: "
+  read profile
+  qrencode -t ansiutf8  < $profile.conf
+  exit
+fi
 
 if [ "$parameter" == "down" ] ; then
   if [ "$active_profile" != "" ] ; then
